In [1]:
import numpy as np

In [4]:
lista = [i for i in range(1,10)]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr = np.array(lista)

In [11]:
type(arr)


numpy.ndarray

In [12]:
matrix = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Indexing

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[0]

1

In [16]:
arr[0] + arr[5]

7

In [17]:
matrix 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matrix[0]

array([1, 2, 3])

In [21]:
matrix[0][2]

3

In [22]:
matrix[0,2]

3

#Slicing

In [23]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [24]:
arr[::3] #Trae todos los elementos del arreglo pero de 3 en 3

array([1, 4, 7])

In [25]:
arr[-1]

9

In [26]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])