In [1]:
import numpy as np

In [7]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [9]:
conditional_arr = arr > 5
conditional_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr[0:5]

array([1, 2, 3, 4, 5], dtype=int8)

In [12]:
arr[conditional_arr]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [15]:
arr[(conditional_arr) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [16]:
arr[arr> 5 ] = 99 
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [18]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)