In [1]:
import numpy as np

In [2]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand()

0.15347128974692814

In [13]:
np.random.rand(4)

array([0.22864618, 0.66503809, 0.56547058, 0.61743899])

In [14]:
np.random.rand(4,4)

array([[0.80915891, 0.95538342, 0.67325433, 0.57468571],
       [0.13511697, 0.44061334, 0.15126118, 0.05392587],
       [0.94626957, 0.54251767, 0.21337652, 0.30416137],
       [0.43807174, 0.42417526, 0.16096579, 0.16142563]])

In [48]:
np.random.randint(10)

2

In [50]:
np.random.randint(1,15)

12

In [51]:
np.random.randint(1,100,(10,10))

array([[95, 27, 19, 24, 25, 94, 53, 72, 16, 38],
       [56, 44,  1, 31, 24, 84, 19, 39, 51, 47],
       [13, 19, 16, 83, 44, 25,  1, 12, 34,  5],
       [15, 59, 48, 81, 82, 70, 87, 44, 21, 92],
       [73, 16, 63, 39, 69, 92, 82, 85, 20, 10],
       [39, 53, 54, 57, 38, 10, 44,  5, 90,  3],
       [56,  9, 77, 83, 57, 65, 30, 31, 40, 43],
       [83, 79, 83, 13, 31, 33, 69, 53, 61, 97],
       [95, 22, 54, 74, 50,  1, 48, 97, 15, 51],
       [23, 46, 13, 32, 66, 41, 82, 80, 66, 33]])