In [2]:
import numpy as np


In [7]:
scalar = np.array(42)
print(scalar)

42


In [8]:
scalar.ndim

0

In [11]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

## Agregar o eliminar dimensiones

In [14]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [17]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim


[[1 2 3]]


2

In [18]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
