In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,21,10)
arr

array([15, 14, 15, 19,  9,  6, 14,  2,  3,  5])

In [6]:
matrix = arr.reshape(2,5)
matrix

array([[15, 14, 15, 19,  9],
       [ 6, 14,  2,  3,  5]])

In [8]:
arr.max()

19

In [10]:
matrix.max()

19

In [13]:
matrix.max(0) # 0 para columna 1 para fila

array([15, 14, 15, 19,  9])

In [14]:
arr.argmax() #Muestra el índice del elemento más alto

3

In [17]:
matrix.argmax(1) # Muestra el índice del elemento más alto en las filas

array([3, 1])

In [18]:
arr.min()

2

In [19]:
matrix.min()

2

In [20]:
matrix.min(1)

array([9, 2])

In [21]:
arr.argmin()

7

In [22]:
arr


array([15, 14, 15, 19,  9,  6, 14,  2,  3,  5])

In [23]:
arr.ptp() # Pick  to pick, es la diferencia entre el valor maximo y el valor minimo

17

In [28]:
matrix.ptp(0)

array([ 9,  0, 13, 16,  4])

In [31]:
np.percentile(arr,10) #Percentil 

2.9

In [29]:
arr.sort()
arr

array([ 2,  3,  5,  6,  9, 14, 14, 15, 15, 19])

In [30]:
np.median(arr) #Mediana

11.5

In [32]:
np.median(matrix)

11.5

In [33]:
np.median(matrix,0)

array([ 8. ,  8.5, 10. , 10.5, 14. ])

In [34]:
np.std(arr)

5.635601121442148

In [36]:
np.std(matrix,1)

array([2.44948974, 1.8547237 ])

In [37]:
np.var(arr)

31.759999999999998

In [38]:
np.mean(arr)

10.2

In [39]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [41]:
b = np.array([5, 6])
b

array([5, 6])

In [42]:
np.concatenate(a,b,axis=0)

TypeError: concatenate() got multiple values for argument 'axis'

In [43]:
a.ndim

2

In [44]:
b.ndim

1

In [45]:
b = np.expand_dims(b, axis=0)

In [47]:
print(b, b.ndim)

[[5 6]] 2


In [49]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [51]:
a

array([[1, 2],
       [3, 4]])

In [52]:
b

array([[5, 6]])

In [54]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [55]:
b.T

array([[5],
       [6]])