In [1]:
import numpy as np

In [4]:
arr = np.random.randint(0, 100, (3,2))
arr

array([[50, 79],
       [26, 71],
       [53, 26]])

In [5]:
arr.shape


(3, 2)

In [6]:
arr.reshape(1,6)

array([[50, 79, 26, 71, 53, 26]])

In [10]:
arr.reshape(2,3)

array([[50, 79, 26],
       [71, 53, 26]])

In [12]:
arr

array([[50, 79],
       [26, 71],
       [53, 26]])

In [11]:
np.reshape(arr,(2,3),'C')

array([[50, 79, 26],
       [71, 53, 26]])

In [13]:
np.reshape(arr,(2,3),'F')

array([[50, 53, 71],
       [26, 79, 26]])

In [14]:
np.reshape(arr,(2,3),'A')

array([[50, 79, 26],
       [71, 53, 26]])